### ISSUE TITLE
Functions need to be improved

### ISSUE THREAD

**Issue by zazaulola** [victorqribeiro/TinyJS#7]
```
  window['$'] = selector => document.querySelector(selector)
  window['$$'] = selector => Array.from(document.querySelectorAll(selector))
```
Pay attention to the function header in the documentation.

https://developer.chrome.com/docs/devtools/console/utilities#querySelector-function
https://developer.chrome.com/docs/devtools/console/utilities#querySelectorAll-function

Both functions can accept an optional second parameter, where you can specify the root of the element search. This can be vital when working with tree structures of elements, when you need to find not all elements on the page, but only elements within a certain branch of elements.

I thought of a solution to this problem a few years ago.

So far, this is the implementation I've come up with. 

Here functions can take from one parameter to an unlimited number of parameters. The functions will look for selectors sequentially next within the previous one. Unlike the DevTools implementation, functions read parameters from left to right. 

```javascript
/**
 * Query Selector
 * @function $
 * @param  {...{object|string}} q query
 * @returns {Node}
 */

function $(...q) {
  return !q.length
    ? null
    : Array.isArray(q[0])
      ? $(q[0].reduce((r, s, i) => ((r += (i ? q[i] : "") + s), r), ""))
      : q.reduce(
        (r, s) => (!r ? null : s instanceof Node ? s : r.querySelector(s)),
        document
      );
}

/**
  * Query Selector All
  * @function $$
  * @param  {...{Node|string}} q query
  * @returns {NodeList}
  */
function $$(...q) {
  return !q.length
    ? []
    : Array.isArray(q[0])
      ? $$(q[0].reduce((r, s, i) => ((r += (i ? q[i] : "") + s), r), ""))
      : q.reduce(
        (r, s) =>
          !r
            ? []
            : s instanceof Node
              ? [s]
              : s instanceof NodeList
                ? [...s]
                : Array.isArray(s) && s.every(e => e instanceof Node)
                  ? s
                  : [...new Set(r.map(p => [...p.querySelectorAll(s)]).flat())],
        [document]
      );
}

```

In the DevTools implementation, the root of the search is specified by the second parameter, which may not be obvious to people who do not speak Arabic, Hebrew, Persian, Urdu and Sindhi. Left to right is much more readable in my opinion. But if we still need a variant that will require to specify parent elements to the right of child elements, we just need to replace `.reduce() `with `.reduceRight()` in two places of the implementation.

The function can take both selectors and element objects as the root of the search.

All variants work:

```javascript
$( 'ul li:last-child' ).innerHTML            // => 3
$( 'ul', 'li:last-child' ).innerHTML         // => 3
$( $( 'ul' ), 'li:last-child' ).innerHTML    // => 3
$`ul li:last-child`.innerHTML                // => 3
  // in 
  //   <ul>
  //     <li> 1 </li>
  //     <li> 2 </li>
  //     <li> 3 </li>
  //   </ul>
```

```javascript
$$( 'ul li:last-child' )               // => [ <li> 1.3 </li>, <li> 2.3 </li>, <li> 3 </li> ]
$$( 'ul', 'li:last-child' )            // => [ <li> 1.3 </li>, <li> 2.3 </li>, <li> 3 </li> ]
$$( $( 'ul' ), 'li:last-child' )       // => [ <li> 1.3 </li>, <li> 2.3 </li>, <li> 3 </li> ]
$$`li:last-child`                      // => [ <li> 1.3 </li>, <li> 2.3 </li>, <li> 3 </li> ]
$$( 'ul li:nth-child(2)', 'ul li:last-child' )  // => [ <li> 2.3 </li> ]
  // in
  //    <ul>
  //      <li>
  //        <p> 1 </p>
  //        <ul>
  //          <li> 1.1 </li>
  //          <li> 1.2 </li>
  //          <li> 1.3 </li>
  //        </ul>
  //      </li>
  //      <li>
  //        <p> 2 </p>
  //        <ul>
  //          <li> 2.1 </li>
  //          <li> 2.2 </li>
  //          <li> 2.3 </li>
  //        </ul>
  //      </li>
  //      <li> 3 </li>
  //    </ul>
```

**Comment by victorqribeiro** [comment]
Although I appreciate the explanation and the code examples with tests, I'm not willing to alter the functions on TinyJS. I'd prefer to keep it simple with less code as possible, and when selecting an element people can target it via the selector.
