### ISSUE TITLE
Add list render [enhancement]

### ISSUE THREAD

**Issue by troshkinpavel** [victorqribeiro/TinyJS#8]
Hi! I propose my own variant for displaying nested arrays of elements.
You have an assignDeep function, I suggest you also add an appendDeep function like this (+ a slightly reworked assignDeep):

`  const assignDeep = (elm, props) => Array.isArray(props) ? elm.append(...props) : Object.entries(props).forEach(([key, value]) => typeof value === 'object' ? assignDeep(elm[key], value) : Object.assign(elm, {[key]: value})) `

`  const appendDeep = (elm, args) => elm.prepend(...args.map(a => typeof a == 'string' ? document.createTextNode(a) : (Array.isArray(a) ? (appendDeep(elm, a) || '') : a)))`

The output will be the ability to make such structures:
![image](https://github.com/user-attachments/assets/423be19c-5100-4779-ab04-46ba62479e29)

**Comment by victorqribeiro** [comment]
Just use the spread operator

![image](https://github.com/user-attachments/assets/fb4c92ce-1b69-49a8-a9dc-77cc954b896e)
